### PR TITLE
Files converted to Typescript from Javascript. Logic separated out in…

### PR DESCRIPTION
**Pull request by benhcai**
…to different components with closely related functions and variables moved closer to the relevant components.

Tracing has been restructured for readability and separation of concerns. The package now first treats tracing/index as the entrypoint.

Pages have been renamed to include _ where page routes are not meant to exist.

### CODE REVIEW

**Comment by gilessteiner1** [comment]
Great work. Lets implement typescript functionality after launch as we are feature locked.

**Review by Mr-Mercury — APPROVED** [review]
Logical changes, nothing looks out of place.  Good base for further expansion.  Gave you approval to merge, clean up the conflicts so you can merge.

**Comment by benhcai** [comment]
Thank you for the attentive review, team! Great suggestions that should definitely be patched before merge. I've gone and implemented your suggestions to the branch and updated the branch pull request.

**Review by gilessteiner1 — APPROVED** [review]
Great work here ben.

**Pull request merged**
